# used for developement when application is run with dev profile
server:
    port: 8082
    address: localhost

https:
    port: 8445

opal:
    url: https://localhost:8443
    username: administrator
    password: password

agate:
    url: https://localhost:8444
    application:
        name: mica
        key: changeit

elasticsearch:
    dataNode: true
    clusterName: mica
    shards: 5
    replicas: 1
    settings: "http.enabled: true"
    maxConcurrentJoinQueries: 2
    concurrentJoinQueriesWaitTimeout: 15000

shiro:
    password:
        nbHashIterations: 10000
        salt: mica

#
# Other advanced settings
#

plugins:
  updateSite: https://plugins.obiba.org

spring:
    profiles: dev
    data:
        mongodb:
            uri: mongodb://localhost:27017/mica
    mail:
        host: localhost
        port: 25
        user:
        password:
        protocol: smtp
        tls: false
        auth: false

# You can add as many as folders to watch
# You just need to add a dash + the directory to watch
hotReload:
    enabled: true
    package:
        project: org.obiba.mica
        domain: org.obiba.mica.domain
        restdto: org.obiba.mica.web.rest.dto
    watchdir:
        - target/classes

sets:
  cleanup:
    # "<second> <minute> <hour> <day-of-month> <month> <day-of-week> <year>"
    # Current cron set to run every day at mid-night
    cron: "0 0 * * * ?"

#
# Cors Configuration
# @Params : allowCredentials : boolean (true, false)
# @Params : allowedOrigins : String ("http://Domaine1.com,http://domaine2.com,http://domaine3.com ...", "*")
# @Params : allowedMethods : String ("OPTIONS,GET,POST,PUT,DELETE ...", "*")
# @Params : allowedHeaders : String ("Accept,Content-type ...", "*")
# @Params : maxAge : Long (0 ~ 3600 etc..)
#

#cors:
#  allowCredentials: true
#  allowedOrigins: "http://localhost:8088"
#  allowedMethods: "OPTIONS,GET,POST"
#  allowedHeaders: "*"
